posts/urls.py
from django.conf.urls import url

from .views import posts, newpost, details, edit, delete


urlpatterns =[
    url(r'^$', posts, name = 'posts'),
    url(r'new$', newpost, name = 'new'),
    url(r'^edit/(?P<id>\d+)/$', edit, name='edit'),
    url(r'^delete/(?P<id>\d+)/$', delete, name='delete'),
    url(r'^(?P<id>\d+)/$', details, name='details'),
]

svrea/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render

from .views import (
    index,
    gindex,
    legal,
    fav_timeseries,
    fav_hist,
    maps_density,
    maps_listings,
    plots_histograms,
    plots_timeseries,
    plots_general
)

from svrea_script.views import script_info as svrea_script_info
from svrea_script.views import script_data as svrea_script_data
from svrea_script.views import script_run as svrea_script_run
from svrea_script.views import script_logs as svrea_script_logs

from uauth.views import uregister

def notfound(request):
    return render(request, '404.html')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^tables/', include('tables.urls', namespace='tables')),
    url(r'^$', index, name = 'index'),
    url(r'googleb070a3405a28a8d0.html', gindex, name = 'gindex'),
    url(r'^legal/', legal, name = 'legal'),
    url(r'^register/', uregister, name = 'register'),
    url(r'^users/', include('users.urls', namespace = 'users')),
    #url(r'maps/(?P<map_type>\w+)$', maps, name = 'maps'),
    url(r'favourite/timeseries$', fav_timeseries, name = 'fav_timeseries'),
    url(r'favourite/histograms$', fav_hist, name = 'fav_hist'),
    url(r'maps/density$', maps_density, name = 'maps_density'),
    url(r'maps/listings$', maps_listings, name = 'maps_listings'),
    url(r'plots/general$', plots_general, name = 'plots_general'),
    url(r'plots/histograms$', plots_histograms, name = 'plots_histograms'),
    url(r'plots/timeseries$', plots_timeseries, name = 'plots_timeseries'),
    url(r'script_info$', svrea_script_info, name = 'script_info'),
    url(r'script_run$', svrea_script_run, name = 'script_run'),
    url(r'script_logs$', svrea_script_logs, name = 'script_logs'),
    url(r'script_data$', svrea_script_data, name = 'script_data'),
    url(r'^404.html', notfound),
]

tables/urls.py
from django.conf.urls import url

from .views import index, summary


urlpatterns =[
    url(r'^$', index, name = 'summary'),
    url(r'summary$', summary, name = 'summary'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <title>Real Estate Analytics for Sweden</title>
    <meta name="description" content="Get a Fresh Daily Dose of Real Estate Anaytics in Sweden">
    <meta name="keywords" content="Real Estate,Property,Analytics,Analysis,Sweden,Bostad,Sverige">
    <meta name="author" content="Shavorskiy">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href=" {% static "css/bootstrap.min.css" %}" type="text/css"/>
    <link rel="stylesheet" href=" {% static "css/bootstrap-multiselect.css" %}" type="text/css"/>
    <link rel="stylesheet" href=" {% static "css/bootstrap-example.css" %}" type="text/css">

    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap-multiselect.js" %}"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:500,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{%static "css/base.css"%}">
    {% block styles %}
    {% endblock %}





    {% block head %}
    {% endblock %}



</head>
<body>
    <div class="full">
        <div class="text-center blue">
            <a href="{% url 'index' %}" style="text-decoration: none;"><h1 class="rea">SVREA</h1></a>
            <h1 style="font-size: 18pt"> Real Estate Analytics for Sweden</h1>
        </div>
        {% include "messages_display.html" %}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        {% if perms.posts.add_posts %}
                         <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">News <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href='{% url "posts:posts"  %}'>All</a></li>
                                <li><a href='{% url "posts:new"  %}'>New</a></li>
                            </ul>
                        </li>
                        {% else %}
                        <li><a href="{% url 'posts:posts' %}">News</a></li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Favourite <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href='{% url "fav_hist"  %}'>Histograms</a></li>
                                <li><a href='{% url "fav_timeseries"  %}'>Time Series</a></li>
                            </ul>
                        </li>
                        {% endif %}

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Maps <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href='{% url "maps_density" %}'>Density Map</a></li>
                                <li><a href='{% url "maps_listings" %}'>Property Map</a></li>

                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Plots <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href='{% url "plots_general"  %}'>Summary</a></li>
                                <li><a href='{% url "plots_histograms"  %}'>Histograms</a></li>
                                <li><a href='{% url "plots_timeseries"  %}'>Time Series</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tables <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href='{% url "tables:summary"  %}'>Summary</a></li>
                            </ul>
                        </li>
                        {% if perms.svrea_script.can_see_history or perms.svrea_script.can_run_script %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Script <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                {% if perms.svrea_script.can_see_info %}
                                    <li><a href='{% url "script_info"  %}'>Info</a></li>
                                {% endif %}
                                {% if perms.svrea_script.can_run_script %}
                                    <li><a href='{% url "script_run"  %}'>Run</a></li>
                                {% endif %}
                                {% if perms.svrea_script.can_see_script_logs %}
                                    <li><a href='{% url "script_logs"  %}'>Logs</a></li>
                                {% endif %}
                                {% if perms.svrea_script.can_see_data %}
                                    <li><a href='{% url "script_data"  %}'>Data</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                    <div class="logOut">
                    {% if request.user.is_authenticated %}
                        <form class="navbar-form navbar-right" method="post">
                            {% csrf_token %}
                            <button type="submit" value="Log Out" name="submit" class="btn btn-default">Log Out</button>
                        </form>
                        <p class="navbar-text navbar-right">Welcome, {{ request.user.username }}!</p>
                    {% else %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'register' %}">Register</a></li>
                        </ul>
                        <form class="navbar-form navbar-right" method="post" name="login">
                            {% csrf_token %}
                            <input type="text" class="form-control" placeholder="User Name" name = "username">
                            <input type="password" class="form-control" placeholder="Password" name="password">
                            <button type="submit" value="Log In" name="submit" class="btn btn-default">Log In</button>
                        </form>
                    {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    {% block content %}
    {% endblock %}

            <div class="text-center blue">
                Posted by: <a href="mailto:andrey.shavorskiy@gmail.com">Andrey Shavorskiy</a>. <a href="{% url 'legal' %}">Disclaimer</a>
            </div>

    </div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-104489770-1', 'auto');
  ga('send', 'pageview');

</script>
</body>

</html>

templates/googleb070a3405a28a8d0.html
google-site-verification: googleb070a3405a28a8d0.html

templates/messages_display.html
{% if messages%}
    <style>
        .messages_err{
            color: Red ;
            background-color: orange;
            font-size: 100%;
            font-family: "Trebuchet MS", Helvetica, sans-serif;
            margin-bottom: 1%;
            text-align: center;
        }
        .messages_default{
            color: SteelBlue ;
            background-color: LightBlue;
            font-size: 100%;
            font-family: "Trebuchet MS", Helvetica, sans-serif;
            margin-bottom: 1%;
            text-align: center;
        }
    </style>
            {% for message in messages%}
                <div class="{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    messages_err
                {% else %}
                    messages_default
                {% endif %}">
                    {{message | safe}}<br/>
                </div>
            {% endfor %}
{% endif %}